### ISSUE TITLE
Podman 1.4.0 complains about 'podman cp --pause=true ...'

### ISSUE THREAD

**Issue by mildred** [debarshiray/toolbox#198]
Running `toolbox enter` it fails with the following message:

```
toolbox: resolved absolute path for /home/mildred/.local/bin/toolbox to /var/home/mildred/Projects/fedora-toolbox/toolbox
toolbox: checking if /etc/subgid and /etc/subuid have entries for user mildred
toolbox: TOOLBOX_PATH is /var/home/mildred/Projects/fedora-toolbox/toolbox
toolbox: checking if 'podman system migrate' exists
toolbox: migration not needed: 1.4.0 is unchanged
toolbox: Fedora generational core is f30
toolbox: base image is fedora-toolbox:30
toolbox: container is fedora-toolbox-30
toolbox: checking if container fedora-toolbox-30 exists
toolbox: container fedora-toolbox-30 not found
toolbox: container fedora-toolbox-mildred-30 found
toolbox: calling org.freedesktop.Flatpak.SessionHelper.RequestSession
toolbox: trying to start container fedora-toolbox-mildred-30
toolbox: looking for /etc/profile.d/toolbox.sh in container fedora-toolbox-mildred-30
Error: exit status 1
toolbox: copying /etc/profile.d/toolbox.sh to container fedora-toolbox-mildred-30
Error: cannot copy into running rootless container with pause set - pass --pause=false to force copying
toolbox: unable to copy /etc/profile.d/toolbox.sh to container fedora-toolbox-mildred-30
```

I don't know what's wring. it happened after upgrading fedora silverblue to latest 30.20190616.0 (podman 1.4.0-2.fc30). Trying to add `--pause=false` to `podman cp` command-line does not help. Instead, I get:

```
toolbox: copying /etc/profile.d/toolbox.sh to container fedora-toolbox-mildred-30
Error: error copying "/etc/profile.d/toolbox.sh" to "/var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh/toolbox.sh": mkdir /var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh: not a directory
toolbox: unable to copy /etc/profile.d/toolbox.sh to container fedora-toolbox-mildred-30
```

**Comment by mildred** [comment]
The container is not started prior to `toolbox enter`.

**Comment by debarshiray** [comment]
> Error: cannot copy into running rootless container with pause set - pass
> --pause=false to force copying

That was a minor regression that crept into Podman 1.4.0. It is addressed in Toolbox by #193 and #194.

**Comment by debarshiray** [comment]
> Error: error copying "/etc/profile.d/toolbox.sh" to "/var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh/toolbox.sh": mkdir /var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh: not a directory

I believe that this is related to a regression in `podman cp` that I uncovered the other day. Some time after `podman-1.2.0`, it started creating `/etc/profile.d/toolbox.sh` inside the container as a directory, instead of a regular file.

**Comment by mike-nguyen** [comment]
> > Error: error copying "/etc/profile.d/toolbox.sh" to "/var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh/toolbox.sh": mkdir /var/home/mildred/.local/share/containers/storage/overlay/5b1b73c12d081d0e62c88b945e349ea161342a268276f889f0e5aee5b293396f/merged/etc/profile.d/toolbox.sh: not a directory
> 
> I believe that this is related to a regression in `podman cp` that I uncovered the other day. Some time after `podman-1.2.0`, it started creating `/etc/profile.d/toolbox.sh` inside the container as a directory, instead of a regular file.

I'm trying to get toolbox running on Fedora CoreOS and ran into the same error.  If I add a sleep before https://github.com/debarshiray/toolbox/blob/bc1a816ea3b80fc7c3dc5d523838256e94c953d2/toolbox#L288 it works fine.  If I take the sleep out, I get the error above.

**Comment by grdryn** [comment]
I get this error message even when my container is started (I guess it was started on the first attempt when I hit the failure?). Not sure if any of the below info is useful or not, just thought I'd put it here in case. I've tried to run the command without the redirect & custom message that `toolbox` adds, to see what the `podman` message is:

```
$ podman ps
CONTAINER ID  IMAGE                              COMMAND     CREATED      STATUS             PORTS  NAMES
31191e2f1277  localhost/fedora-toolbox-gryan:30  sleep +Inf  7 weeks ago  Up 22 minutes ago         fedora-toolbox-gryan-30

$ podman cp --pause=false /etc/profile.d/toolbox.sh fedora-toolbox-gryan-30:/etc/profile.d
Error: error copying "/etc/profile.d/toolbox.sh" to "/var/home/gryan/.local/share/containers/storage/overlay/71a012bda72f39db9c7e73af1b5071aa78a077f5fc12daeefabf5dd8204166a3/merged/etc/profile.d/toolbox.sh/toolbox.sh": mkdir /var/home/gryan/.local/share/containers/storage/overlay/71a012bda72f39db9c7e73af1b5071aa78a077f5fc12daeefabf5dd8204166a3/merged/etc/profile.d/toolbox.sh: not a directory
```

When I try to list that containers storage path that's in the error message, it bottoms out at the `merged/` directory, so maybe that `mkdir` needs a `-p` in podman?

```
$ ls -al ~/.local/share/containers/storage/overlay/71a012bda72f39db9c7e73af1b5071aa78a077f5fc12daeefabf5dd8204166a3/merged/
total 8
drwx------. 2 gryan gryan 4096 Apr 25 22:37 .
drwx--x--x. 5 gryan gryan 4096 Apr 25 22:37 ..
```

If I create the path on my host, that doesn't seem to help though, so that `mkdir` might be a red herring, not sure.

Oddly, the file does exist in the container as expected (might be there from before the issue started with podman 1.4.0):

```
$ podman exec fedora-toolbox-gryan-30 md5sum /etc/profile.d/toolbox.sh
7bb7f37bea2f13c77681999e05ba0df2  /etc/profile.d/toolbox.sh
$ md5sum /etc/profile.d/toolbox.sh
7bb7f37bea2f13c77681999e05ba0df2  /etc/profile.d/toolbox.sh
```

I created this bz for the issue on Fedora a couple of days ago, there are a couple of other comments there from others: https://bugzilla.redhat.com/show_bug.cgi?id=1719993

**Comment by grdryn** [comment]
I still experience this with toolbox 0.0.11 and podman 1.4.2:

```
rpm -q podman toolbox
podman-1.4.2-1.fc30.x86_64
toolbox-0.0.11-1.fc30.noarch
```

**Comment by debarshiray** [comment]
> > Error: cannot copy into running rootless container with pause set - pass
> > --pause=false to force copying
> 
> That was a minor regression that crept into Podman 1.4.0. It is addressed in Toolbox by #193 and #194.

I am going to close this because the original bug has been fixed and released as `toolbox-0.0.11`.

I understand that a lot of people have been running into problems involving `podman cp`. However, they are not all the same problem. For all those problems, I'd encourage you to try https://github.com/debarshiray/toolbox/pull/202

Let's keep this issue restricted to this one thing.
